replicaCount: 1

image:
  repository: jaipalreddyg/sample-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 80
  targetPort: 8000

ingress:
  enabled: false
  host: app.example.com
  certificateArn: arn:aws:acm:ap-south-1:434779526479:certificate/REPLACE
  scheme: internet-facing

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 65

health:
  path: /
  initialDelaySeconds: 10

podDisruptionBudget:
  minAvailable: 0

